global:
  scrape_interval:     15s
  evaluation_interval: 15s
rule_files:
scrape_configs:
  - job_name: 'spring-actuator'
    basic_auth:
      username: rahul
      password: rahul1234
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    metrics_path: 'actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.7:8081']
        labels:
         group: 'springboot-info'
         application: 'cricketmatch'

  - job_name: 'cricketmatch-actuator'
    basic_auth:
      username: rahul
      password: rahul1234
    scheme: 'https'
    tls_config:
      insecure_skip_verify: true
    metrics_path: 'actuator/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.1.7:8081']
        labels:
          group: 'scoreboard'
          application: 'cricketmatch'