version: '3'
services:
  mysql-standalone:
    image: mysql:8.0
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=scoreboard
      - MYSQL_USER=rahul
      - MYSQL_PASSWORD=abc123
    ports:
      - 3306:3306

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://mysql-standalone:3306/scoreboard -schemas=scoreboard -user=rahul -password=abc123 -connectRetries=60 migrate
    volumes:
      - .:/db/migration/sqlserver
    depends_on:
      - mysql-standalone

  scoreboard:
    image: vikasdimri/scoreboard:1.0.0
    depends_on:
      - mysql-standalone
      - rabbitmq
      - flyway
    restart: always
    ports:
      - 8081:8081
