apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  serviceName: "mysql"
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: scoreboard
            - name: MYSQL_USER
              value: rahul
            - name: MYSQL_PASSWORD
              value: abc123
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage-1
              mountPath: /var/lib/mysql
            - name: mysql-persistent-storage-2
              mountPath: /var/lib/mysql
            - name: mysql-persistent-storage-3
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage-1
          persistentVolumeClaim:
            claimName: mysql-pv-claim-1
        - name: mysql-persistent-storage-2
          persistentVolumeClaim:
            claimName: mysql-pv-claim-2
        - name: mysql-persistent-storage-3
          persistentVolumeClaim:
            claimName: mysql-pv-claim-3
